apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
  namespace: default  # You can change 'default' to your desired namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: bhargavjupalli/backend-app:1.0.0
          ports:
            - containerPort: 3333  # Container port where your app is running
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default  # Ensure this matches the namespace in the deployment
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 9092  # Port exposed to the outside world
      targetPort: 3333  # Port inside the container
  type: LoadBalancer  # Exposes the service externally
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: default  # Ensure this matches the namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ec2-13-127-197-254.ap-south-1.compute.amazonaws.com  # Replace with your actual EC2 public DNS
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 9092  # Match the port exposed by the service
