apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
  namespace: default  # Add the namespace field (you can change 'default' to a custom namespace if needed)
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-container
          image: bhargavjupalli/backend-app:1.0.0
          ports:
            - containerPort: 3333  # Updated port to 9091
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default  # Add the namespace field
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 9092       # Updated port to 9091
      targetPort: 3333   # Ensure it matches the containerPort defined above
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: default  # Add the namespace field
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ec2-13-127-197-254.ap-south-1.compute.amazonaws.com # Replace with your actual EC2 IP or domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3333  # Match the port used in the service and deployment
